version: '3.8'
services:
  promethus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    entrypoint: ""
    command: ["k6", "run", "/scripts/myscript.js"]

networks:
    monitoring-network:
        driver: bridge
