spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  jwt:
    secret: ${JWT_SECRET_KEY}


